# SPDX-License-Identifier: GPL-2.0-only
#
# linux/arch/riscv/crypto/Makefile
#

obj-$(CONFIG_CRYPTO_AES_RISCV_SCALAR) += aes-riscv-scalar.o
aes-riscv-scalar-y := aes-riscv-scalar-glue.o aes-riscv$(BITS)-zkned.o
