// SPDX-License-Identifier: GPL-2.0
/*
 * CFB: Cipher FeedBack mode
 *
 * Copyright (c) 2018 James.Bottomley@HansenPartnership.com
 * Copyright (c) 2023 Google LLC
 *
 * CFB is a stream cipher mode which is layered on to a block
 * encryption scheme.  It works very much like a one time pad where
 * the pad is generated initially from the encrypted IV and then
 * subsequently from the encrypted previous block of ciphertext.  The
 * pad is XOR'd into the plain text to get the final ciphertext.
 *
 * The scheme of CFB is best described by wikipedia:
 *
 * https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#CFB
 *
 * Note that since the pad for both encryption and decryption is
 * generated by an encryption operation, CFB never uses the block
 * decryption function.
 */

#include <crypto/algapi.h>
#include <crypto/internal/cipher.h>
#include <crypto/internal/skcipher.h>
#include <linux/err.h>
#include <linux/init.h>
#include <linux/kernel.h>
#include <linux/module.h>
#include <linux/string.h>

static void crypto_cfb_encrypt_one(struct crypto_cipher *tfm, u8 *dst,
				   const u8 *src, unsigned int bs,
				   unsigned int alignmask)
{
	/*
	 * 'dst' is always sufficiently aligned, so if 'src' does not meet the
	 * alignment constraint of the underlying cipher, copy the block into
	 * 'dst' first, and perform the encryption in place.
	 */
	if (unlikely(alignmask > 0 &&
		     !IS_ALIGNED((unsigned long)src, alignmask + 1))) {

		BUG_ON(!IS_ALIGNED((unsigned long)dst, alignmask + 1));
		src = memcpy(dst, src, bs);
	}

	crypto_cipher_alg(tfm)->cia_encrypt(crypto_cipher_tfm(tfm), dst, src);
}

/*
 * Aligning a stack allocation to 16 bytes may not work as expected
 * on x86, so increase the alignment to 32 bytes in that case.
 */
#if defined(CONFIG_X86) && (MAX_CIPHER_ALIGNMASK == 15)
#define CIPHER_ALIGN	32
#else
#define CIPHER_ALIGN	(MAX_CIPHER_ALIGNMASK + 1)
#endif

static int crypto_cfb_crypt(struct skcipher_request *req, bool decrypt)
{
	struct crypto_skcipher *tfm = crypto_skcipher_reqtfm(req);
	struct crypto_cipher *cipher = skcipher_cipher_simple(tfm);
	unsigned long alignmask = crypto_cipher_alignmask(cipher);
	unsigned int bs = crypto_cipher_blocksize(cipher);
	u8 __aligned(CIPHER_ALIGN) ks[2][MAX_CIPHER_BLOCKSIZE];
	struct skcipher_walk walk;
	int err, i = 0;

	/* ensure that both ks[] slots are sufficiently aligned */
	static_assert((MAX_CIPHER_BLOCKSIZE & MAX_CIPHER_ALIGNMASK) == 0);

	err = skcipher_walk_virt(&walk, req, false);

	crypto_cfb_encrypt_one(cipher, ks[0], walk.iv, bs, alignmask);

	while (walk.nbytes > 0) {
		bool last = (walk.nbytes == walk.total);
		const u8 *src = walk.src.virt.addr;
		u8 *dst = walk.dst.virt.addr;
		unsigned int nbytes = walk.nbytes;

		/*
		 * The only difference between CFB encryption and decryption is
		 * the order of the XOR and AES operations, as it involves
		 * using the preceding block of ciphertext to generate a key
		 * stream.
		 */
		do {
			unsigned int l = min(nbytes, bs);

			if (!decrypt)
				crypto_xor_cpy(dst, src, ks[i], l);

			if (nbytes > bs || !last) {
				const u8 *ctxt = decrypt ? src : dst;

				/*
				 * Create the keystream for the next iteration
				 * from the current iteration's ciphertext.
				 */
				crypto_cfb_encrypt_one(cipher, ks[!i], ctxt,
						       bs, alignmask);
			}

			if (decrypt)
				crypto_xor_cpy(dst, src, ks[i], l);

			dst += l;
			src += l;
			nbytes -= l;
			i ^= 1;
		} while (nbytes >= bs || (last && nbytes > 0));

		err = skcipher_walk_done(&walk, nbytes);
	}

	memzero_explicit(ks, sizeof(ks));
	return err;
}

static int crypto_cfb_encrypt(struct skcipher_request *req)
{
	return crypto_cfb_crypt(req, false);
}

static int crypto_cfb_decrypt(struct skcipher_request *req)
{
	return crypto_cfb_crypt(req, true);
}

static int crypto_cfb_create(struct crypto_template *tmpl, struct rtattr **tb)
{
	struct skcipher_instance *inst;
	struct crypto_alg *alg;
	int err;

	inst = skcipher_alloc_instance_simple(tmpl, tb);
	if (IS_ERR(inst))
		return PTR_ERR(inst);

	alg = skcipher_ialg_simple(inst);

	/* don't propagate cipher alignmask to the caller */
	inst->alg.base.cra_alignmask = 0;

	/* CFB mode is a stream cipher. */
	inst->alg.base.cra_blocksize = 1;

	/*
	 * To simplify the implementation, configure the skcipher walk to only
	 * give a partial block at the very end, never earlier.
	 */
	inst->alg.chunksize = alg->cra_blocksize;

	inst->alg.encrypt = crypto_cfb_encrypt;
	inst->alg.decrypt = crypto_cfb_decrypt;

	err = skcipher_register_instance(tmpl, inst);
	if (err)
		inst->free(inst);

	return err;
}

static struct crypto_template crypto_cfb_tmpl = {
	.name = "cfb",
	.create = crypto_cfb_create,
	.module = THIS_MODULE,
};

static int __init crypto_cfb_module_init(void)
{
	return crypto_register_template(&crypto_cfb_tmpl);
}

static void __exit crypto_cfb_module_exit(void)
{
	crypto_unregister_template(&crypto_cfb_tmpl);
}

subsys_initcall(crypto_cfb_module_init);
module_exit(crypto_cfb_module_exit);

MODULE_LICENSE("GPL");
MODULE_DESCRIPTION("CFB block cipher mode of operation");
MODULE_ALIAS_CRYPTO("cfb");
MODULE_IMPORT_NS(CRYPTO_INTERNAL);
